### ISSUE TITLE
Shortcut not recognizing files

### ISSUE THREAD

**Issue by mistermonn** [ognistik/km-ai-memos#3]
Hi, 

This is a wonderful tool! 

I have a problem implementing it, as I get this error message when starting the Shortcut with Keyboard Maestro: 

> Invalid file format. Supported formats: ['flac', 'm4a', 'mp3', 'mp4', 'mpeg', 'mpga', 'oga', 'ogg', 'wav', 'webm']

Any suggested solutions? :) 

Regards, 
Magnus

**Comment by ognistik** [comment]
Oh, that's interesting. Did you try using the Shortcut alone to record & transcribe? Did it work there? In this error message you are getting, is it when you are running the entire automation with Just Press Record? Can you guide me a little bit through your process to see if I can replicate it? 

By using Just Press Record, by the way, in my settings of the app I got to record on AAC (.m4a) but honestly any of the available options should work.

**Comment by mistermonn** [comment]
Yes, the Shortcut works perfectly on its own. The issue only arrises when starting the automation from Just Press Record, or when trying to run the Keyboard Maestro automation by itself. 

I’ve redownloaded and tested it multiple times, but I keep encountering the same error. This happens whether I’m sending a note directly to Notes or using my adapted version of the Shortcut that sends notes to Obsidian.

**Comment by ognistik** [comment]
Ok, it's still not clear for me where the error message is showing up - in the shortcut, the resulting note, or in Keyboard Maestro as an alert or notification. Since you said the shortcut works fine by itself, I think the problem might be either Just Press Record file or Keyboard Maestro.

**Here's what you can try first:** Take a recording from Just Press Record and share it directly with the shortcut (You may need to deactivate the KM Macro first). If this works and gives you a transcription in your note, then Just Press Record isn't the issue. This would mean the problem is likely with the Keyboard Maestro macro.

If that's the case, I can give you a version with some alert messages that will show us what's happening during the process. You can deactivate the official/current macro and try this one instead. It will show you which file is being sent to OpenAI for transcription, and the result you get back. There's four alerts, the first two should give you the path to the file about to be sent, then after rename... if one of those is wrong, doesn't include anything, or it's not the correct file then just select cancel and let me know. The last two alerts should give you results you get from OpenAI. The moment you see an error you can let me know. 

Keep in mind that when you run the full automation with Just Press Record and Keyboard Maestro, the transcription doesn't happen in the shortcut. The shortcut, in this case, only makes one quick request to create the note title. The actual audio transcription happens in Keyboard Maestro. That's why we'll add an alert in there to see which file is going to OpenAI's servers. 

This should help us spot the problem, especially if you can transcribe the same file successfully using just the shortcut.

[AI Memos.kmmacros.zip](https://github.com/user-attachments/files/17607721/AI.Memos.kmmacros.zip)

**Comment by patemouille** [comment]
Hi Robert,

Thank you for your reply on YouTube and for pointing me to the GitHub discussion—it’s been very helpful.

After further testing, sharing .m4a or .wav files directly with the AI Memos shortcut works perfectly. However, when placing the same file in the Just Press Record folder, Keyboard Maestro triggers and immediately displays the “Invalid file format” error ([screenshot](https://dropover.cloud/2fd969)).

Following the alerts in the macro, the final API request to OpenAI fails with this error:

	“This is the entire response from OpenAl's Request. It should contain your raw transcribed audio. If it doesn't, you can select cancel:
	"error": (
	"message": "You didn't provide an API key. You need to provide
	your API key in an Authorization header using Bearer auth (i.e.
	Authorization: Bearer YOUR_KEY), or as the password field (with
	blank username) if you're accessing the API from your browser and
	are prompted for a username and password. You can obtain an API
	key from https://platform.openai.com/account/api-keys."',
	"type": "invalid_request _error",
	"param": null,
	"code": null”

I suspect the issue might come from the “Run Shortcut” action in Keyboard Maestro. I disabled all other actions and still received the same error ([screenshot](https://dropover.cloud/46dbea)). Unfortunately, I’m not sure how to resolve this.

If you have any insights or suggestions, I’d really appreciate your help.

Thanks again for your support!
Best regards,

**Comment by ognistik** [comment]
Hey @patemouille,

Thanks for testing this. Would you mind going through some more troubleshooting with me? That API request failure alert makes sense - the "Run Shortcut" action is what transfers your information from the shortcut to Keyboard Maestro. If your API token isn't getting through, the request will fail.

From what I'm seeing, the error might be in the shortcut itself. Let's verify this by testing the Keyboard Maestro action block you showed in your screenshot:

1. Find "Run Shortcut" block.
2. Click where it says "Save results to variable"
3. Change the setting from "Save results to variable" to "Display results in a window"
4. Right-click on that "Run Shortcut" block and select "Try action"

This will test just that single action and confirm if the shortcut is causing the problem. [Check this screenshot with these same instructions for clarity.](https://a.dropoverapp.com/cloud/download/2f9a7ebb-1358-4b70-8ff6-ea5eef16b96b/cf605b8a-b1d3-4127-8313-4fbf67bc9a5b)

If that action is working correctly, you should see some information popup: an AI system prompt, custom settings, the info you input in the Shortcut (DON'T screenshot this for me, it includes your API token). If you see the same error, then this sounds like one of those weird bugs that Apple sometimes has with the Shortcuts app. I'll make a version with the Shortcut with some debugging Alerts as I did with the macro before. Just confirm with me and we'll go from there.

**Comment by patemouille** [comment]
Hello @ognistik,

Thank you so much for your detailed reply and instructions—I really appreciate it!

I followed the steps you provided to test the “Run Shortcut” action by changing “Save results to variable” to “Display results in a window” and running it. However, no Keyboard Maestro window popped up. Instead, I immediately received the [same error message from the shortcut itself](https://dropover.cloud/bbdc93).

Could this issue be related to the fact that my Mac is set to French rather than English? I wonder if this might affect how the shortcut interacts with Keyboard Maestro or handles variables.

Let me know if you think this could be a factor or if there’s anything else I should try.

Thanks again for your help!

**Comment by ognistik** [comment]
Great! Happy to know that we actually found the block with the issue. Try to download [this Shortcut](https://www.icloud.com/shortcuts/0b5747de3dec4eb6ae0ace0fc3df1416) which should help us a bit more find out the issue. I'm on my way out so I did [THIS QUICK VIDEO](https://preview.screen.studio/share/AQa5hz8R) explaining what to do this, if you can't follow along (or have some issues with the video) let me know and I'll come back and type a step by step. Let me know the results or how it goes!

**Comment by patemouille** [comment]
Thanks, @ognistik!!!

The issue was indeed related to my Mac’s language settings. I changed “Dictionary” to “Dictionnaire,” and everything is now working perfectly!

Thank you so much for this Shortcut—it’s going to be incredibly helpful in my daily life. I truly appreciate your guidance and all the time you spent helping me solve this issue!

Best regards,
Sam

**Comment by ognistik** [comment]
I'm very glad to know and I think this will also be great for other international users!
